/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stoplimit2;

import java.awt.AWTException;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author YOUCEF2
 */
public class StopLimitFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form StopLimitFrame2
     */
    public StopLimitFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtCeck = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnCheck = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtCeck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCeckActionPerformed(evt);
            }
        });

        jLabel1.setText("Now Price");

        BtnCheck.setText("Check");
        BtnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCheckActionPerformed(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(TxtCeck, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BtnCheck)
                        .addGap(239, 239, 239)
                        .addComponent(jButton1)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCheck)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCeckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCeckActionPerformed

    private void BtnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCheckActionPerformed
        
         try {
            go g = new go();
            CoinRobot c = new CoinRobot();
            String afterchange =g.CheckAndChangePoint(TxtCeck.getText());
           
            
             double diffrent = Double.parseDouble(afterchange)-Double.parseDouble(g.Get("NOW_PRICE"));
             
        if (diffrent > 0) {
            g.ChangeStopLitmitPrice(diffrent);
            g.ChangeNowPrice(Double.parseDouble(afterchange));
            c.oneLeftClickWithMouse(820, 570);// close the first program
            c.wait(50);
            c.oneLeftClickWithMouse(290, 870);// open the browser
            c.wait(50);
            c.oneLeftClickWithMouse(1220, 800);// cancel the old order
            c.wait(50);
            c.oneLeftClickWithMouse(740, 485);// confrmation of cancel the oreder
            c.wait(50);
            c.MouseMove(950, 598);
            c.wait(50);
            c.HoldMouse();
            c.wait(50);
            c.MouseMove(860, 598);
            c.wait(50);
            c.LetHoldMouse();
            c.wait(150);
            c.Typing(g.Get("STOP_LIMIT_PRICE"));// typinf the ,=new priccz
            c.wait(150);
            c.MouseMove(950, 627);
            c.wait(50);
            c.HoldMouse();
            c.MouseMove(860, 627);
            c.wait(50);
            c.LetHoldMouse();
            c.wait(150);
            c.Typing(g.Get("STOP_LIMIT_PRICE"));// typinf the ,=new priccz
            c.wait(150);
            c.oneLeftClickWithMouse(1010, 670); //100%
            c.wait(150);
            c.oneLeftClickWithMouse(900, 730);// put the order
            c.wait(50);
            c.oneLeftClickWithMouse(740, 490);// confrmation of the oreder
            c.wait(50);
            c.oneLeftClickWithMouse(1506, 12);// hide the brwoser
             c.wait(50);
            c.oneLeftClickWithMouse(820, 570);// close the first programc.wait(100);
            c.wait(50);
            c.oneLeftClickWithMouse(220, 800);// open the first program
            c.wait(50);
            c.pressKeybord(KeyEvent.VK_ENTER);// pres enter for open the first program
            c.wait(150);
            c.oneLeftClickWithMouse(750, 575);//run the first prgram
            
        } else {
            c.wait(50);
            c.oneLeftClickWithMouse(820, 570);// close the first programc.wait(100);
            c.wait(50);
            c.oneLeftClickWithMouse(220, 800);// open the first program
            c.wait(50);
            c.pressKeybord(KeyEvent.VK_ENTER);// pres enter for open the first program
            c.wait(150);
            c.oneLeftClickWithMouse(750, 575);//run the first prgram
              }
         } catch (AWTException ex) {
            Logger.getLogger(StopLimitFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }





///////////////////////////////////////////////////////////////////////////////////////////////////
       /* try {
            go g = new go();
            CoinRobot c = new CoinRobot();
            String afterchange =g.CheckAndChangePoint(TxtCeck.getText());
           
            
             double diffrent = Double.parseDouble(afterchange)-Double.parseDouble(g.Get("NOW_PRICE"));
             
        if (diffrent > 0) {
            g.ChangeStopLitmitPrice(diffrent);
            g.ChangeNowPrice(Double.parseDouble(afterchange));
            c.wait(100);
            c.oneLeftClickWithMouse(1208, 805);
            c.wait(100);
            c.oneLeftClickWithMouse(660, 545);
            c.wait(100);
            c.MouseMove(950, 598);
            c.HoldMouse();
            c.wait(100);
            c.MouseMove(870, 598);
            c.LetHoldMouse();
            c.Typing(g.Get("STOP_LIMIT_PRICE"));
            c.wait(100);
            //
            //c.wait(100);
            c.MouseMove(950, 625);
            c.HoldMouse();
            c.wait(100);
            c.MouseMove(870, 625);
            c.LetHoldMouse();
            c.Typing(g.Get("STOP_LIMIT_PRICE"));
            c.wait(100);
            c.oneLeftClickWithMouse(1010, 670);
            c.wait(500);
            c.oneLeftClickWithMouse(900, 730);
            c.wait(100);
            c.oneLeftClickWithMouse(1506, 12);
            c.wait(100);
            c.oneLeftClickWithMouse(820, 570);
            c.wait(100);
            c.oneLeftClickWithMouse(30, 880);
            c.wait(100);
            c.Typing("mkmlksdijkjasbijj.java");//fitst program
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_ENTER);
            c.oneLeftClickWithMouse(750, 575);
            
            
            
            
        } else {
            c.wait(100);
            c.oneLeftClickWithMouse(1506, 12);
            c.wait(100);
            c.oneLeftClickWithMouse(820, 570);
            c.wait(100);
            c.oneLeftClickWithMouse(30, 880);
            c.wait(100);
            c.Typing("mkmlksdijkjasbijj.java");//fitst program
            c.wait(500);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_DOWN);
            c.wait(200);
            c.pressKeybord(KeyEvent.VK_ENTER);
            c.wait(200);
            c.oneLeftClickWithMouse(750, 575);
               
            

        }
         } catch (AWTException ex) {
            Logger.getLogger(StopLimitFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }*/ //////////////////////////////////////////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_BtnCheckActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopLimitFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StopLimitFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCheck;
    private javax.swing.JTextField TxtCeck;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
